### ISSUE TITLE
Empty repo

### ISSUE THREAD

**Issue by BenDz** [netagence/WPATI_Xiti#1]
Hello,
I can't find the plugin files in the repo, is it normal?
Thank you!

**Comment by netagence** [comment]
Hello,

The plugin is being worked on in another repository, this one was opened for future publication as we were not aware anybody had an interest yet. If you don't mind beta stages we'll consider publishing sooner ;-)

**Comment by BenDz** [comment]
Take your time! 
If we (AT Internet) can help in any way, don't hesitate to get back to me! :)

**Comment by netagence** [comment]
Hello,
As you'll see the repo was updated with a working version of the plugin.
I'd be interested in checking a few things with you about some features.
We may also proceed by email and in French :-)

Have a nice day.

**Comment by BenDz** [comment]
Thanks for the update!
Don't hesitate to drop me an email at benjamin.diolez@atinternet.com (in French ;))
